### ISSUE TITLE
why  detection result can't  show  in video?

### ISSUE THREAD

**Issue by so-as** [scotthuang1989/object_detection_with_tensorflow#1] opened 2017-10-23 11:22 UTC
Hi, Mr huang. When I run your demo in the terminal:  `python3 object_detection_tf.py -v pathto/crossing.avi`，the result seems unnormal. 
The terminal output below:<pre> image worker start
detection worker start
2017-10-24 03:18:02.817987: W tensorflow/core/platform/cpu_feature_guard.cc:45]      The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are      available on your machine and could speed up CPU computations.
2017-10-24 03:18:02.818090: W tensorflow/core/platform/cpu_feature_guard.cc:45]      The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are      available on your machine and could speed up CPU computations.
2017-10-24 03:18:02.818107: W tensorflow/core/platform/cpu_feature_guard.cc:45]      The TensorFlow library wasn't compiled to use AVX instructions, but these are av     ailable on your machine and could speed up CPU computations.
2017-10-24 03:18:02.818121: W tensorflow/core/platform/cpu_feature_guard.cc:45]      The TensorFlow library wasn't compiled to use AVX2 instructions, but these are a     vailable on your machine and could speed up CPU computations.
2017-10-24 03:18:02.818141: W tensorflow/core/platform/cpu_feature_guard.cc:45]      The TensorFlow library wasn't compiled to use FMA instructions, but these are av     ailable on your machine and could speed up CPU computations.
2017-10-24 03:18:03.303367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9     40] Found device 0 with properties:
name: Tesla M40
major: 5 minor: 2 memoryClockRate (GHz) 1.112
pciBusID 0000:82:00.0
Total memory: 11.93GiB
Free memory: 11.72GiB
2017-10-24 03:18:03.303462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9     61] DMA: 0
2017-10-24 03:18:03.303482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9     71] 0:   Y
2017-10-24 03:18:03.303518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1     030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla M40, pci bus id: 0000:82:00.0)
time for a frame: 5.0267462730407715 </pre>
Just first frame was detected, and cv2.imshow() didn't work. what went wrong?
I was run in ubuntu14.04 with tensorflow 1.2. thank you @scotthuang1989

**Comment by scotthuang1989** [comment] 2017-10-23 12:03
I think the problem is because opencv and related libs are not installed properly.  opencv relies on other libs to support GUI function. my environment is ubuntu 16.04, I follow this [tutorial](https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/) to setup opencv, this website also have ubuntu 14.04 tutorial, you can try it  [link](https://www.pyimagesearch.com/2015/07/20/install-opencv-3-0-and-python-3-4-on-ubuntu/)

**Comment by scotthuang1989** [comment] 2017-11-04 15:10
I close the issue, because I don't get your response for 12 days.

**Closed as completed** 2017-11-04 15:10 UTC

**Comment by so-as** [comment] 2017-11-10 12:50
I finally found the problem is `ann_image = cv2.cvtColor(ann_image, cv2.COLOR_RGB2BGR)`. when I replace `ann_image = ann_image[:, :, ::-1]`, the detection result image can show. thank you very much @scotthuang1989

**Comment by scotthuang1989** [comment] 2017-11-10 13:25
This is very strange, because all  `ann_image = cv2.cvtColor(ann_image, cv2.COLOR_RGB2BGR)`  tryin g to do is change color channel from B G R to  R G B, this is exactly what your code trying to do!

**Comment by so-as** [comment] 2017-11-11 13:06
yes, I know. I found some strange things when I use some functions of opencv library. for example,  cv2.resize can work, but I use in my code can cause program crash. haha
